name: Terraform CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        # Possibly uses a backend that doesn't require secrets or has read-only credentials

      - name: Terraform Plan
        run: terraform plan -no-color
        # Show the plan result in PR checks, but not applying yet
